"""Update column in payment table

Revision ID: 340abc828850
Revises: 36b0c53c0dfc
Create Date: 2024-07-25 15:04:06.478179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340abc828850'
down_revision: Union[str, None] = '36b0c53c0dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    op.alter_column('payment', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'amount',
               existing_type=sa.Float(precision=10, asdecimal=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('order', 'price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
