"""ADD Delivery boy table in database

Revision ID: 3abf9df90764
Revises: 
Create Date: 2024-07-16 15:36:21.511913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abf9df90764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveryboy',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mo_number', sa.String(length=10), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(mo_number) = 10', name='check_mo_number_length'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('deliveryboy')
    # ### end Alembic commands ###
