"""Add new Column in deliveryboy id in delivery table

Revision ID: 607579194ecb
Revises: 3abf9df90764
Create Date: 2024-07-17 12:34:06.207946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607579194ecb'
down_revision: Union[str, None] = '3abf9df90764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('delivery_boy', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'deliveries', 'deliveryboy', ['delivery_boy'], ['id'])
    op.alter_column('order', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'delivery_boy')
    # ### end Alembic commands ###
