"""ADd user_id in sofa,curtains and mattresses tables

Revision ID: b734ae0da6f5
Revises: 
Create Date: 2024-07-15 16:21:29.988064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b734ae0da6f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curtains', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'curtains', 'users', ['user_id'], ['id'])
    op.add_column('mattresses', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'mattresses', 'users', ['user_id'], ['id'])
    op.alter_column('order', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    op.add_column('sofa', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'sofa', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sofa', type_='foreignkey')
    op.drop_column('sofa', 'user_id')
    op.alter_column('order', 'price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'mattresses', type_='foreignkey')
    op.drop_column('mattresses', 'user_id')
    op.drop_constraint(None, 'curtains', type_='foreignkey')
    op.drop_column('curtains', 'user_id')
    # ### end Alembic commands ###
